pub mod ransomware_sim;
pub mod discovery_sim;
pub mod wifi_creds;
pub mod proc_inj;
pub mod screenshot_sim;
pub mod http_traffic_sim;
pub mod high_cpu_miner_sim;
pub mod ps_elev_whoami;
pub mod add_admin_user;
pub mod open_many_windows;
pub mod ps_defender_exclusions;
pub mod scheduled_task_sim;
pub mod minidump_proc;
pub mod browser_pwd;
pub mod enable_rdp;
pub mod share_enum;
pub mod network_port_scan;
pub mod install_python;
pub mod enable_ssh;
pub mod enable_winrm;
pub mod startup_exec;
pub mod pwd_guessing;
pub mod registry_persistence;
pub mod record_mic;
pub mod keylogger_sim;
pub mod create_proc;
pub mod rev_sh;
pub mod directory_permissions;
pub mod edr_discovery;
pub mod cred_manager_access;


mod macros;
